import { PrismaClient } from "@prisma/client";
import { LogLevel, SapphireClient, container } from "@sapphire/framework";
import { greenBright } from "colorette";
import { type ClientOptions, GatewayIntentBits, Partials } from "discord.js";
import {
	FiftyFiftyParser,
	IfStatementParser,
	RandomParser,
	RangeParser,
	SliceParser,
} from "tagscript";
import { API } from "./api";
import { Tags } from "./tags";

const CLIENT_OPTIONS: ClientOptions = {
	defaultPrefix: "!!",
	regexPrefix: /^(hey +)?zeyr[,! ]/i,
	caseInsensitiveCommands: true,
	logger: {
		level: LogLevel.Debug,
	},
	shards: "auto",
	intents: [
		GatewayIntentBits.GuildModeration,
		GatewayIntentBits.GuildMembers,
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.Guilds,
		GatewayIntentBits.MessageContent,
	],
	partials: [Partials.Channel],
	loadMessageCommandListeners: true,
	subcommandsAdvanced: {
		nameCommandsAutogenerated: true,
	},
};

export class ZeyrClient extends SapphireClient {
	constructor() {
		super(CLIENT_OPTIONS);

		container.prisma = new PrismaClient();
		container.developers = ["1076700780175831100"];
		container.api = new API("http://127.0.0.1:3000");
		container.tags = new Tags(
			new SliceParser(),
			new FiftyFiftyParser(),
			new RandomParser(),
			new IfStatementParser(),
			new RangeParser(),
		);
	}

	public async start(token?: string) {
		container.logger.info(greenBright(""), "Connecting to Discord");
		await super.login(token);
		await container.prisma.$connect();
		container.logger.info(greenBright(""), "Prisma is online now");
	}

	public async panic(error?: unknown) {
		container.logger.fatal(error);
		container.logger.fatal(greenBright(""), "An error occurred, aborting...");
		await super.destroy();
		container.logger.fatal(greenBright(""), "Aborted.");
		await container.prisma.$disconnect();
		container.logger.fatal(greenBright(""), "Turning prisma OFF");
		process.exit(1);
	}
}
