import { LogLevel, SapphireClient, container } from "@sapphire/framework";
import { greenBright } from "colorette";
import { type ClientOptions, GatewayIntentBits, Partials } from "discord.js";
import { API } from "./api";

const CLIENT_OPTIONS: ClientOptions = {
	defaultPrefix: "!!",
	regexPrefix: /^(hey +)?zeyr[,! ]/i,
	caseInsensitiveCommands: true,
	logger: {
		level: LogLevel.Debug,
	},
	shards: "auto",
	intents: [
		GatewayIntentBits.GuildModeration,
		GatewayIntentBits.GuildMembers,
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.Guilds,
		GatewayIntentBits.MessageContent,
	],
	partials: [Partials.Channel],
	loadMessageCommandListeners: true,
	subcommandsAdvanced: {
		nameCommandsAutogenerated: true,
	},
};

export class ZeyrClient extends SapphireClient {
	constructor() {
		super(CLIENT_OPTIONS);

		container.api = new API("http://127.0.0.1:3000");
	}

	public async start(token?: string) {
		container.logger.info(greenBright(""), "Connecting to Discord");
		await super.login(token);
	}

	public async panic(error?: unknown) {
		container.logger.fatal(error);
		container.logger.fatal(greenBright(""), "An error occurred, aborting...");
		await super.destroy();
		container.logger.fatal(greenBright(""), "Aborted.");
		process.exit(1);
	}
}
